config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'home#index'
  root to: 'home#index'
  get 'api/v1/requests/published', to: 'api/v1/requests#published'
  namespace :api do
    namespace :v1 do
      resources :requests do
        resources :descriptions do
        end  
      end
      get 'descriptions', to: 'descriptions#index'
      get 'descriptions/:id', to: 'descriptions#show'
    end    
  end
  get "/help", to: 'home#help'
  post "/help_send", to: 'home#help_send', as: 'help_send'
  get "/fetch_posts", to: 'home#from_category'
  get "/fetch_answered_posts", to: 'requests#from_answered_category'
  get "/fetch_open_posts", to: 'requests#from_open_category'
  get "/requests/open", to: 'requests#open'
  get "/requests/answered", to: 'requests#answered'
  get '/about', to: 'home#about', as: 'about'
  post "requests/add_request", to: 'requests#add_request_home'
  post "requests/open/add_request", to: 'requests#add_request_open'
  # post "requests/:id/answer", to: 'requests#answer', as: 'answer_request'
  post "requests/:id/add_description", to: 'requests#add_description', as: 'request_answer'
  get "/requests/:id", to: 'requests#show',  as: 'request'
  get 'ajax/:action', to: 'ajax#:action', :defaults => { :format => 'js' }
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  include Devise::Controllers
  def from_category 
    clicked_category=params[:category]
    query = "select * from requests where '#{clicked_category}'=ANY(categories) AND status='published' LIMIT 10;"
    result = ActiveRecord::Base.connection.execute(query)
    @requests_published = helper_values(result.values)
    
    respond_to do |format|
      format.js {render layout: false}
    end
  end
  
  def index
    @request = Request.new
    @requests_published = Request.most_recently_added_published
    @requests_approved = Request.most_recently_added_approved
    render :index
  end
  def help
    render :contact
  end
  def about
    render :about
  end
  def help_send
    ContactMailer.send_email.deliver_now
    flash[:notice] = "Your message has been sent. Thank you."
    render :contact
  end
  #NEED TO UPDATE SO IT'S STILL NEWEST FIRST ORDER BY CREATED DESC
  def helper_values(requests)
    new_array = []
    requests.each do |entry|
      obj=Request.new(id:entry[0], content:entry[1], status:entry[2], user_id:entry[3],created_at:entry[4],updated_at:entry[5],categories:entry[6])
      new_array.push(obj)
    end
    new_array
  end
end

app/views/home/about.html.erb
<div style="width:70%; min-width:400px; max-width:850px; margin:50px auto">
  <div id="maincontent" class="about-holder">
    <h3>About Page</h3>
    <br />
    <p>Untold was created primarily for the vision-impaired but also for anyone to <%= link_to "submit requests", requests_open_path %> of things they want visually described or view <%= link_to "answered requests", requests_answered_path %>. Other users can then submit descriptions for each and any request.</p>
    <p>Untold allows users to also upload images. When developing Untold, a vision-impaired person told me they often come across images online that they are curious about; they want to know details about the image. Oftentimes, sites are not accessible as well and lack alt tags on their images. That is why on this site, users can also upload images via link or file upload and ask questions about it.</p>
    <br/>
    <h4>Resources</h4>
    
    <ol><li><a href="https://www.boia.org/blog/5-quick-ways-to-self-check-the-accessibility-of-a-website">https://www.boia.org/blog/5-quick-ways-to-self-check-the-accessibility-of-a-website</a></li><li><a href="https://color.a11y.com/ContrastPair/?bgcolor=1B1D1E&fgcolor=E27D53">https://color.a11y.com/ContrastPair/?bgcolor=1B1D1E&fgcolor=E27D53</a></li></ol>
    </p>
    <br/>
    <h4>GitHub</h4>
    <p>
      This site was created with Ruby on Rails by Morgan Waites. View the GitHub repository <a href="https://github.com/mellowmorgan/untold-app">here</a>!
    </p>
  </div>
</div>

app/views/home/contact.html.erb
<div style="width:50%; min-width:400px; max-width:800px; margin:50px auto">
  <div id="maincontent" class="help-holder">
    <h3>Contact Us</h3>
  
    <div class="help-form">
      <p>Please submit any suggestions for our site, questions, or issues you may be having below.</p><br />
      
      <%= form_with(url: help_send_path, method: :post) do |f| %>
        <div class="form-group">
          <%= f.label "Subject:" %><br />
          <%= f.text_field :subject, :class => 'form-control', 
      placeholder:"Subject" %>
        </div>
        <div class="form-group">
          <%= f.label "Message:" %><br />
          <%= f.text_area :message, :class => 'form-control', 
      placeholder:"Explain your issue here." %>
        </div>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <div>
          <%= f.submit "Answer", :class => "btn btn-light" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/home/from_category.js.erb
$("#published-requests-section").html("<%= escape_javascript(render partial: 'layouts/published_posts', locals: { requests_published: @requests_published} ) %>"); 

app/views/home/index.html.erb
<div class="my-container">
  <div class="row home-row">
    <div class="col-md-2 left-col">
      <%= render 'layouts/sidebar_menu' %>
    </div>
    <div class="col-md-6">
      <%= flash[:notice] %>
      <%= flash[:alert] %>
      <div class="add-request">
        <div class="add-request-title-box">Add a Request</div>
        <div id="maincontent" class="add-request-form">
          <%= form_with(url: "/requests/add_request", method: :post, model: @request, class:"cloudinaryable-form") do |f| %>
            <div class="form-group">
              <%= f.label "Request:" %><br />
              <%= f.text_area :content, :class => 'form-control',  autocomplete: true, 
  placeholder:"Example: What does fire look like?" %><br />
              <%= f.file_field :image, accept: 'image/png, image/gif, image/jpeg', cloud_name: "hkbjwypvm", style:"margin-bottom:8px;", class:"fileInput",direct_upload: true  %><br />
              <%= f.label "Or use an image address:"%>
              <%= f.text_field :image_url, :class => 'form-control fileInput', autocomplete: true %><br />
              <%= f.label "Categories (optional):" %><br />
              <%= f.text_field :categories, :class => 'form-control', autocomplete: true, placeholder:"Example: miscellaneous, nature" %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :status, :value => "approved" %>
            </div>
            <div>
              <%= f.submit "Post", :class => "btn btn-light" %>
            </div>
          <% end %>
        </div>
      </div>

      <div class="answered-requests-home-section-title"> <%= image_tag("squiggle.png",size:"24x24",style:"margin-right:6px;margin-bottom:10px;", alt:"an image of a small cute squiggle just for decoration")%><h3 style="display: inline;"><%= link_to "Answered Requests", requests_answered_path %></h3></div>
      <%= render partial: 'layouts/published_posts', locals: { requests_published: @requests_published} %>
    </div>
    <div class="col-md-4">
      <div class="open-requests-home-section-title"> <%= image_tag("squiggle.png",size:"24x24",style:"margin-right:6px;margin-bottom:10px", alt:"an image of a small cute squiggle just for decoration")%><h3 style="display: inline;"><%= link_to "Open Requests", requests_open_path %></h3>
      </div>
      <div class="open-requests-section-home">
        <div class="open-request-list">
          <% if @requests_approved.any? %>
            <% @requests_approved.each do |request| %>
              <%= link_to request_path(request) do %>
                <div  class="open-request">
                  <h3><%= request.content %></h3> 
              <% end %>
                  <% if request.image.attached? %>
                    <%= cl_image_tag(request.image.key, cloud_name: "hkbjwypvm", class:"request-open-image-home", alt:"image that goes with request: #{request.content}") %>       
                  <% end %>
                  <div style="text-align:right;"><%= button_to "Answer", request_path(request),method: :get, class:"btn btn-light" %></div>
                </div>
            <% end %>
          <% else %>
            <div style="margin:40px;text-align:center;"> <h4>No requests found.</h4></div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
$('.cloudinaryable-form').on('ajax:before', function(submitEvent) {
  if ($('.fileInput').fileupload('active') > 0) {
    submitEvent.preventDefault();
  }
})
</script>