config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'home#index'
  root to: 'home#index'
  get 'api/v1/requests/published', to: 'api/v1/requests#published'
  namespace :api do
    namespace :v1 do
      resources :requests do
        resources :descriptions do
        end  
      end
      get 'descriptions', to: 'descriptions#index'
      get 'descriptions/:id', to: 'descriptions#show'
    end    
  end
  get "/help", to: 'home#help'
  post "/help_send", to: 'home#help_send', as: 'help_send'
  get "/fetch_posts", to: 'home#from_category'
  get "/fetch_answered_posts", to: 'requests#from_answered_category'
  get "/fetch_open_posts", to: 'requests#from_open_category'
  get "/requests/open", to: 'requests#open'
  get "/requests/answered", to: 'requests#answered'
  get '/about', to: 'home#about', as: 'about'
  post "requests/add_request", to: 'requests#add_request_home'
  post "requests/open/add_request", to: 'requests#add_request_open'
  # post "requests/:id/answer", to: 'requests#answer', as: 'answer_request'
  post "requests/:id/add_description", to: 'requests#add_description', as: 'request_answer'
  get "/requests/:id", to: 'requests#show',  as: 'request'
  get 'ajax/:action', to: 'ajax#:action', :defaults => { :format => 'js' }
end

app/models/request.rb
require 'open-uri'
require 'csv'
class Request < ApplicationRecord
  has_one_attached :image
  belongs_to :user
  has_many :descriptions, dependent: :delete_all
  before_save :downcase_categories
  before_save :status_check_nil
  validate :categories_must_exist
  # validates :status, presence: true, inclusion: { in: ["submitted","approved","published","flagged","denied"]}
  scope :most_recently_added_published, -> { where(status:"published").order(updated_at: :desc).limit(7)}
  scope :most_recently_added_all_published, -> { where(status:"published").order(updated_at: :desc)}
  scope :most_recently_added_all_approved, -> { where(status:"approved").order(created_at: :desc)}
  scope :most_recently_added_approved, -> { where(status:"approved").order(created_at: :desc).limit(7)}
  def downcase_categories
    if categories && categories.any?
      self.categories = self.categories.map{|word| word.downcase }
    end
  end
  def status_check_nil
    if !self.status
      self.status = "approved"
    end
  end
  
  def grab_image
    if self.image_url
      
      image_from_url = URI.open(self.image_url)
      self.image.attach(io: image_from_url, filename: "#{self.id}.jpg")
    end
  end
  def categories_must_exist
    valid_categories=["people","popular","nature","miscellaneous","objects", "art", "photography","film","landmarks","buildings","history","animals"]
    valid_checker=true
    if self.categories
      self.categories.each do |word|
        if !valid_categories.include?(word.downcase)
          valid_checker=false
        end
      end
      if self.categories.any? && !valid_checker
        errors.add(:categories, "You've entered an invalid category. Please include one or more of the following categories: people, popular, nature, miscellaneous, objects, history, film, photography, art, landmarks, buildings, animals")
      end
    end
  end
end

app/controllers/api/v1/requests_controller.rb
module Api
  module V1
    class RequestsController < ApplicationController
      def index
        requests = Request.all
        json_response(requests)
      end

      def show
        request = Request.find(params[:id])
        json_response(request)
      end
      
      def published
        requests_published = Request.most_recently_added_published
        if requests_published
          json_response(requests_published)
        else
          render json: { error: "error getting published requests." }
        end
      end
      

      def create
        
        if request_params[:categories]
          str_categories = request_params["categories"]
          array_categories = str_categories.gsub(/\s+/, "").split(",")
        end 
        if !request_params[:categories]
          array_categories = []
        end
        request = Request.new(status:request_params["status"],user_id:request_params["user_id"],content: request_params["content"],categories: array_categories, image_url: request_params["image_url"])
   
        if request.save
          if request.image_url
            request.grab_image
          end
          render status: 200, json: {
          message: "Request added successfully."
          }
        else
          render json: { error: "Unable to create new request." }
        end
      end

      def update
        request = Request.find(params[:id])
        request.update(request_params)
        if request.save
          render status: 200, json: {
            message: "Request updated successfully."
            }
        else
          render json: { error: "There was an error updating the request." }
        end
      end

      def destroy
        request = Request.find(params[:id])
        if request.destroy
          render status: 200, json: {
          message: "Request has been deleted successfully."
          }
        else
          { error: "There was an error deleting the request." }
        end
      end
      private
      
      def request_params
        params.permit(:user_id, :image_url,:content,:status,:categories)
      end
    end
  end
end

app/controllers/requests_controller.rb
require('pry')
class RequestsController < ApplicationController
  include Devise::Controllers
  def from_open_category
    clicked_category=params[:category]
    query = "select * from requests where '#{clicked_category}'=ANY(categories) AND status='approved';"
    result = ActiveRecord::Base.connection.execute(query)
    @requests_approved = helper_values(result.values)
    respond_to do |format|
      format.js {render layout: false}
    end
  end
  def from_answered_category
    clicked_category=params[:category]
    query = "select * from requests where '#{clicked_category}'=ANY(categories) AND status='published';"
    result = ActiveRecord::Base.connection.execute(query)
    @requests_published = helper_values(result.values)
    respond_to do |format|
      format.js {render layout: false}
    end
  end

  def add_description
    request = Request.find(description_params[:request_id])
    description = request.descriptions.new(description_params)
    
    if description.save
      request.update(status:"published")
      flash[:notice] = "Your description has been added."
      redirect_back(fallback_location: root_path)
    else
      errors = ""
      if description.errors.any?
        errors = description.errors.full_messages.join(", ")
      end
      flash[:alert] = "There was an error adding your description. #{errors}."
      
      redirect_back(fallback_location: root_path)
    end
  end
  def add_request_open
    if request_params["image_url"] == ""
      image_url = nil
    else
      image_url = request_params["image_url"]
    end
    if request_params["categories"]
      str_categories = request_params["categories"]
      array_categories = str_categories.gsub(/\s+/, "").split(",")
      request = Request.new(status:request_params["status"],user_id:request_params["user_id"],content: request_params["content"],image_url: image_url,categories: array_categories)
    end
    if request.save
      if request.image_url
        request.grab_image
      elsif request_params[:image]
        request.image.attach(request_params[:image])
      end
      @requests_approved = Request.most_recently_added_all_approved.paginate(page: params[:page], per_page: 10)
      flash[:notice] = "Your request has been added."
      redirect_back(fallback_location: root_path)
    else
      errors = ""
      if request.errors.any?
        errors = request.errors.full_messages.join(", ")
      end
      flash[:alert] = "There was an error adding your request. #{errors}."
      redirect_back(fallback_location: root_path)
    end
  end


  def add_request_home
    if request_strong_params["image_url"] == ""
      image_url = nil
    else
      image_url = request_strong_params["image_url"]
    end
    str_categories = request_strong_params["categories"]
    array_categories = str_categories.gsub(/\s+/, "").split(",")
    request = Request.new(image_url: image_url,status:request_strong_params["status"],user_id:request_strong_params["user_id"],content: request_strong_params["content"],categories: array_categories)
   
    if request.save
      if request.image_url
        request.grab_image
      elsif request_strong_params[:image]
        request.image.attach(request_strong_params[:image])
      end
      
      @requests_approved = Request.most_recently_added_all_approved.paginate(page: params[:page], per_page: 10)
      flash[:notice] = "Your request has been added."
      redirect_back(fallback_location: root_path)
    else
      errors = ""
      if request.errors.any?
        errors = request.errors.full_messages.join(", ")
      end
      flash[:alert] = "There was an error adding your request. #{errors}."
      redirect_back(fallback_location: root_path)
    end
  end
  def open
    @requests_approved = Request.most_recently_added_all_approved.paginate(page: params[:page], per_page: 10)
    render :open
  end
  def answered
    @requests_published = Request.most_recently_added_all_published.paginate(page: params[:page], per_page: 10)
    render :answered
  end
  def show
    @request = Request.find(params[:id])
    render :show
  end
  
  def helper_values(requests)
    new_array = []
    requests.each do |entry|
      obj=Request.new(id:entry[0], content:entry[1], status:entry[2], user_id:entry[3],created_at:entry[4],updated_at:entry[5],categories:entry[6])
      new_array.unshift(obj)
    end
    new_array
  end
  private
  def request_strong_params
    params.require(:request).permit(:user_id, :image, :image_url,:content,:status,:categories)
  end

  def request_params
    params.permit(:user_id, :image, :image_url, :content,:status,:categories)
  end
  def description_params
    params.permit(:user_id, :request_id, :content,:status)
  end
end

app/views/requests/_answered_posts.html.erb
<div class="answered-requests-home-section-title"> <%= image_tag("squiggle.png", alt:"an image of a small cute squiggle just for decoration", size:"24x24",style:"margin-right:6px;margin-bottom:10px;")%><h3 style="display: inline;">Answered Requests</h3></div>
<% if requests_published.any? %>

  <% requests_published.each do |request| %>
    <%= link_to request_path(request) do %>
    <div class="published-request"><h3><%= request.content %></h3>
    <% end %>
    <% if request.image.attached? %>
      <%= cl_image_tag(request.image.key, cloud_name: "hkbjwypvm", class:"request-open-image-show",alt:"image that goes with request: #{request.content}") %>
    <% end %>
    <div class="answer-home"><%= request.descriptions.order(created_at: :desc).first.content %></div>
    </div>
  <% end %>
<% else %>
  <div style="margin:40px;text-align:center;"> <h4>No requests found.</h4></div>
<% end %>

app/views/requests/_open_posts.html.erb
<% if requests_approved.any? %>
  <% requests_approved.each do |request| %>
    <%= link_to request_path(request) do %>
      <div class="open-request"><h3><%= request.content %> </h3><% end %>
      <% if request.image.attached? %>
            
      <%= image_tag(request.image, class:"request-open-image-home") %>
      <% end %>
      <div style="text-align:right"><%= button_to "Answer", request_path(request), method: :get, class:"btn btn-light"%></div>
    </div>
  <% end %>
  <% else %>
  <div style="margin:40px;text-align:center;"> <h4>No requests found.</h4></div>
<% end %>

app/views/requests/answered.html.erb
<div class="my-container">
  <div class="row home-row">
    <div class="col-md-3 left-col">
      <div class="categories">
        <div class="title"><h3>Categories</h3></div>
        <div class="category"><%= link_to "All", root_path %></div>
        <div class="category"><%= link_to "Popular", fetch_answered_posts_path(:category => "popular"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Art", fetch_answered_posts_path(:category => "art"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Photography", fetch_answered_posts_path(:category => "photography"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Film", fetch_answered_posts_path(:category => "film"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Nature", fetch_answered_posts_path(:category => "nature"), :remote => true,data: {type: "script"} %></div>

        <div class="category"><%= link_to "Landmarks", fetch_answered_posts_path(:category => "landmarks"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "People", fetch_answered_posts_path(:category => "people"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Animals", fetch_answered_posts_path(:category => "animals"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Objects", fetch_answered_posts_path(:category => "objects"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Buildings", fetch_answered_posts_path(:category => "buildings"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "History", fetch_answered_posts_path(:category => "history"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Miscellaneous", fetch_answered_posts_path(:category => "miscellaneous"), :remote => true,data: {type: "script"} %></div>
      </div>
    </div>
    <div class="col-md-9">
      <div id="maincontent" class="answered-requests-section">
        <%= render partial: 'answered_posts', locals: { requests_published: @requests_published} %>
        <%= will_paginate @requests_published %>
      </div>
    </div>
  </div>
</div>

app/views/requests/from_answered_category.js.erb
$(".answered-requests-section").html("<%= escape_javascript(render partial: 'answered_posts', locals: { requests_published: @requests_published} ) %>"); 

app/views/requests/from_open_category.js.erb
$("#open-requests-section").html("<%= escape_javascript(render partial: 'open_posts', locals: { requests_approved: @requests_approved} ) %>"); 

app/views/requests/open.html.erb
<div class="my-container">
  <div class="row home-row">
    <div class="col-md-3 left-col">
      <div class="categories">
        <div class="title"><h3>Categories</h3></div>
        <div class="category"><%= link_to "All", root_path %></div>
        <div class="category"><%= link_to "Popular", fetch_open_posts_path(:category => "popular"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Art", fetch_open_posts_path(:category => "art"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Photography", fetch_open_posts_path(:category => "photography"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Film", fetch_open_posts_path(:category => "film"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Nature", fetch_open_posts_path(:category => "nature"), :remote => true,data: {type: "script"} %></div>

        <div class="category"><%= link_to "Landmarks", fetch_open_posts_path(:category => "landmarks"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "People", fetch_open_posts_path(:category => "people"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Animals", fetch_open_posts_path(:category => "animals"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Objects", fetch_open_posts_path(:category => "objects"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Buildings", fetch_open_posts_path(:category => "buildings"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "History", fetch_open_posts_path(:category => "history"), :remote => true,data: {type: "script"} %></div>
        <div class="category"><%= link_to "Miscellaneous", fetch_open_posts_path(:category => "miscellaneous"), :remote => true,data: {type: "script"} %></div>
      </div>
    </div>
    <div class="col-md-9">
      <divid="maincontent" class="open-requests-section">
        <div class="open-requests-home-section-title" style="margin-top:0;"> <%= image_tag("squiggle.png",size:"24x24",alt:"an image of a small cute squiggle just for decoration", style:"margin-right:6px;margin-bottom:10px")%><h3 style="display: inline;">Open Requests</h3></div>
        <%= flash[:notice] %>
        <%= flash[:alert] %>

        <div class="add-request">
          <div class="add-request-title-box">Add a Request</div>
          <div class="add-request-form">
            <%= form_with(url: "/requests/open/add_request", method: :post, model: @request) do |f| %>
            <div class="form-group">
              <%= f.label "Request:" %><br />
              <%= f.text_area :content, :class => 'form-control',  autocomplete: true, 
              placeholder:"What does fire look like?" %><br />
              <%= f.label "Upload an image (optional):"%><br />
              <%= f.file_field :image, accept: 'image/png, image/gif, image/jpeg', style:"margin-bottom:8px;",direct_upload: true %><br />
              <%= f.label "Or use an image address:"%>
              <%= f.text_field :image_url, :class => 'form-control', autocomplete: true %>
              <br />
              <%= f.label "Tags (optional):" %><br />
              <%= f.text_field :categories, :class => 'form-control', autocomplete: true, placeholder:"Example: miscellaneous, nature" %>
              <%= f.hidden_field :user_id, :value => current_user.id %>
              <%= f.hidden_field :status, :value => "approved" %>
            </div>
            <div>
              <%= f.submit "Post", :class => "btn btn-light" %>
            </div>
          <% end %>

          </div>
        </div>
        <div id="open-requests-section">

          <%= render partial: 'open_posts', locals: { requests_approved: @requests_approved} %>
          <%= will_paginate @requests_approved %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/requests/show.html.erb
<div id="maincontent" class="my-container">
  <div class="author-username" style="width:60%; margin:auto; margin-top:50px;">
    <%= flash[:notice] %>
    <%= flash[:alert] %>
    <h2><%= @request.content %></h2>
    <h5>Request Author: <%= link_to User.find(@request.user_id).username, root_path %></h5>
    <% if @request.image.attached? %>
      <%= cl_image_tag(@request.image.key, cloud_name: "hkbjwypvm", class:"request-open-image-show", alt:"image that goes with request: #{@request.content}") %>
    <% end %>
    <div class="add-description" style="margin-top:50px;">
      <div class="add-description-title-box">Answer this Request</div>
      <div class="add-description-form">
        <%= form_with(url: request_answer_path, method: :post, model: @description) do |f| %>
        <div class="form-group">
          <%= f.label "Description:" %><br />
          <%= f.text_area :content, :class => 'form-control', 
  placeholder:"Visual description goes here." %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :request_id, :value => @request.id %>
          <%= f.hidden_field :status, :value => "published" %>
        </div>
        <div>
          <%= f.submit "Answer", :class => "btn btn-light" %>
        </div>
      <% end %>
    </div>
    </div>
    <div style="margin-top:50px;margin-left:20px;"> <h4><%=@request.descriptions.length%> <% if @request.descriptions.length==1 %>Answer<% else %>Descriptions<% end %></h4></div>
    <div>
      <% if @request.status=="published" && @request.descriptions.any? %>
        <% @request.descriptions.reverse.each do |desc| %>
          <div class="published-desc">
            <%= desc.content %>
            <h5>Description Author: <%= link_to User.find(desc.user_id).username, root_path %></h5>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>