config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root to: 'home#index'
  root to: 'home#index'
  get 'api/v1/requests/published', to: 'api/v1/requests#published'
  namespace :api do
    namespace :v1 do
      resources :requests do
        resources :descriptions do
        end  
      end
      get 'descriptions', to: 'descriptions#index'
      get 'descriptions/:id', to: 'descriptions#show'
    end    
  end
  get "/help", to: 'home#help'
  post "/help_send", to: 'home#help_send', as: 'help_send'
  get "/fetch_posts", to: 'home#from_category'
  get "/fetch_answered_posts", to: 'requests#from_answered_category'
  get "/fetch_open_posts", to: 'requests#from_open_category'
  get "/requests/open", to: 'requests#open'
  get "/requests/answered", to: 'requests#answered'
  get '/about', to: 'home#about', as: 'about'
  post "requests/add_request", to: 'requests#add_request_home'
  post "requests/open/add_request", to: 'requests#add_request_open'
  # post "requests/:id/answer", to: 'requests#answer', as: 'answer_request'
  post "requests/:id/add_description", to: 'requests#add_description', as: 'request_answer'
  get "/requests/:id", to: 'requests#show',  as: 'request'
  get 'ajax/:action', to: 'ajax#:action', :defaults => { :format => 'js' }
end

app/views/layouts/_published_posts.html.erb
<div id="published-requests-section">
  <% if requests_published.any? %>
   
    <% requests_published.each do |request| %>
      <%= link_to request_path(request) do %>
        <div class="published-request">
          <h3><%= request.content %></h3>
      <% end %>
        <% if request.image.attached? %>
          <%= cl_image_tag(request.image.key,cloud_name: "hkbjwypvm", alt:"image that goes with request: #{request.content}", class:"request-answered-image-home", style:"padding-top:8px") %>
        <% end %>
         
        <div class="answer-home" style="text-decoration:none !important">
            Answer: <%= request.descriptions.order(created_at: :desc).first.content %>
        </div>    
      </div>
    <% end %>
  <% else %>
    <div style="margin:40px;text-align:center;"> <h4>No requests found.</h4></div>
  <% end %>
</div>

app/views/layouts/_sidebar_menu.html.erb
<div class="categories">
  <div class="title"><h3>Categories</h3></div>
  <div class="category"><%= link_to "All", root_path %></div>
  <div class="category"><%= link_to "Popular", fetch_posts_path(:category => "popular"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Art", fetch_posts_path(:category => "art"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Photography", fetch_posts_path(:category => "photography"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Film", fetch_posts_path(:category => "film"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Nature", fetch_posts_path(:category => "nature"), :remote => true,data: {type: "script"} %></div>

  <div class="category"><%= link_to "Landmarks", fetch_posts_path(:category => "landmarks"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "People", fetch_posts_path(:category => "people"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Animals", fetch_posts_path(:category => "animals"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Objects", fetch_posts_path(:category => "objects"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Buildings", fetch_posts_path(:category => "buildings"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "History", fetch_posts_path(:category => "history"), :remote => true,data: {type: "script"} %></div>
  <div class="category"><%= link_to "Miscellaneous", fetch_posts_path(:category => "miscellaneous"), :remote => true,data: {type: "script"} %></div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untold</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag asset_path('squiggle.png') %>
  </head>  
  
  <% if user_signed_in? %>
    <body>
      <nav class="my-nav-bar">
        <div class="nav-title"><h2><%= link_to "untold", root_path %></h2></div>
        <div class="links-nav">
        <a href="#maincontent">Skip to main content</a>
        <%= link_to "Home", root_path %>
        <%= link_to "About", about_path %>
        <%= link_to "Contact Us", help_path %>
        <%= link_to "Edit Account", edit_user_registration_path %> 
        <%= link_to('Logout', destroy_user_session_path, method: :delete) %>       
        </div>
      </nav>  
      <%= yield %>
    </body> 
  <% else %>

    <%= yield %>

  <% end %>
</html>